### ISSUE TITLE
Allow Scenarios and Components to be written in ES6

### ISSUE THREAD

**Issue by MattiSG** [MattiSG/Watai#31]
That's one case where CS would be a better fit than JS: many hashes, little nesting, very simple accessors.

**Comment by MattiSG** [comment]
ES6 now. Ideas:

```js
/**added**/
let MyComponent = new Component();
MyComponent.init((function() { return /** /added **/{
  root: 'body',
  field: 'input[name=q]',
  submitButton: '#search_button_homepage',

  search: (query) => [
    this.field.set(query),
    this.submitButton.click()
  ]
}
/**added**/}).bind(MyComponent));/** /added **/
```

```js
export default class Search extends Component {
  constructor() {
    super();
    this.root = 'body';
    this.field = 'input[name=q]';
    this.submitButton = '#search_button_homepage';
  }

  search(query) {
    return [
      this.field.set(query),
      this.submitButton.click()
    ]
  }
}
```
```yaml
root: body
field: input[name=q]
submitButton: #search_button_homepage

search:
  - field.set(query)
  - submitButton.click()
```
